{
 "title": "Kubernetes Cluster CPU",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "node", "query": ".*" },
   { "name": "namespace", "query": ".*" }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_system_seconds_total{id=\"/\"}[1m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU Requested",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[1m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU Allocatable",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "CPU" }
   ],
   "targets": [
    {
     "expr": "sum (machine_cpu_cores) - sum (rate (container_cpu_system_seconds_total{id=\"/\"}[1m]))",
     "legendFormat": "allocatable"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    { "expr": "sum (machine_cpu_cores)", "legendFormat": "total" }
   ]
  }
 ]
}