{
    "apiVersion": 1,
    "datasources": [
        {
           "access":"proxy",
           "editable": true,
           "name": "prometheus-ext",
           "orgId": 1,
           "type": "prometheus",
           "url": "http://8.208.113.89:9090",
           "version": 1
        }
    ]
}
