apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: v1.8.0
  name: kube-state-metrics
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: telemetry
    port: 8081
    targetPort: 8081
    nodePort: 30081
  selector:
    app.kubernetes.io/name: kube-state-metrics
