---
- hosts: metrics_and_consul_server
  user: root
  become: yes
  tasks:
    - name: Create alertmanager user
      user:
        name: alertmanager
        state: present
        shell: /bin/bash       
        system: no             
        createhome: yes
    - name: "Downloading Alertmanager"
      get_url:
        url: https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
        dest: /opt/alertmanager-0.21.0.linux-amd64.tar.gz
        mode: 0644
    - name: "Extract Alertmanager Package"
      unarchive:
        src: /opt/alertmanager-0.21.0.linux-amd64.tar.gz
        dest: /opt
        remote_src: yes
    - name: "Copy binaries to /usr/local/bin"
      copy:
        src: /opt/alertmanager-0.21.0.linux-amd64/{{ item }}
        dest: /usr/local/bin/{{ item }}
        owner: alertmanager
        group: alertmanager
        mode: 0755
        remote_src: yes
      with_items:
        - alertmanager
        - amtool
    - name: make directory
      file:
        path: "{{ item }}"
        state: directory
        owner: alertmanager
        group: alertmanager
      with_items:
        - "/etc/alertmanager"
    - name: "create alertmanager.yml file"
      copy:
        src: "<path-to-here>/ansible/alertmanager/alertmanager.yml"
        dest: "/etc/alertmanager/alertmanager.yml"
        owner: alertmanager
        group: alertmanager
    - name: "create service file for Alertmanager"
      copy:
        src: "<path-to-here>c/ansible/alertmanager/alertmanager.service"
        dest: "/usr/lib/systemd/system/alertmanager.service"
    - name: " Starting and Enabling Alertmanager service"
      service:
        name: alertmanager
        state: started
        enabled: yes
        daemon-reload: yes











